const STORE='nitka';let D=JSON.parse(localStorage.getItem(STORE)||'{}');
if(!D.users)D={users:{},threads:{},posts:{},messages:{},currentUserId:null,readPosts:{},notifications:{},theme:'dark'};
const U=D.users,T=D.threads,P=D.posts,M=D.messages;let CUID=D.currentUserId,CU=CUID?U[CUID]:null;
const $=id=>document.getElementById(id),content=$('content'),authArea=$('authArea');

function save(){localStorage.setItem(STORE,JSON.stringify(D));}
function av(u){return u.avatar?`<img src="${u.avatar}" class="avatar">`:`<div class="avatar donut">🍩</div>`;}
function role(u){if(u.isCreator)return'<span class="role-tag creator">Создатель</span>';if(u.premium)return'<span class="role-tag premium">⭐ Премиум</span>';if(u.adminClubs&&u.adminClubs.length)return'<span class="role-tag admin">Админ</span>';return'<span class="role-tag guest">Гость</span>';}
function notif(to,type,from,ex={}){if(!D.notifications[to])D.notifications[to]=[];D.notifications[to].push({type,from,time:Date.now(),read:false,...ex});if(D.notifications[to].length>30)D.notifications[to]=D.notifications[to].slice(-30);save();updateBell();}
function updateBell(){const n=CU?D.notifications[CUID]||[]:[];const unread=n.filter(x=>!x.read).length;const b=$('notifCount');b.style.display=unread?'inline':'none';if(unread)b.textContent=unread;}
function toggleNotifPanel(){const p=$('notifPanel');if(p.style.display==='block'){p.style.display='none';return;}const n=CU?D.notifications[CUID]||[]:[];p.innerHTML=n.length?n.reverse().map(x=>{const f=U[x.from]||{name:'Система'};return`<div style="padding:5px;">${x.type==='like'?'❤️ '+f.name+' лайкнул пост':x.type==='comment'?'💬 '+f.name+' прокомментировал':x.type==='subscribe'?'👤 '+f.name+' подписался':'ℹ️ Уведомление'}</div>`}).join(''):'<p>Нет уведомлений</p>';p.style.display='block';if(CU){D.notifications[CUID].forEach(x=>x.read=true);save();updateBell();}}
function achievements(){if(!CU)return;const a=CU.achievements||[];const posts=Object.values(P).filter(p=>p.authorId===CUID);const likes=posts.reduce((s,p)=>s+(p.likes?.length||0),0);const followers=Object.values(U).filter(u=>u.subscribedAuthors?.includes(CUID)).length;const threads=Object.values(T).filter(t=>t.ownerId===CUID&&t.type==='user').length;const comments=Object.values(P).reduce((s,p)=>s+(p.comments?.filter(c=>c.userId===CUID).length||0),0);const clubs=Object.values(T).filter(t=>t.type==='club'&&t.members?.includes(CUID)).length;const add=t=>{if(!a.includes(t))a.push(t);};if(posts.length>=1)add('🌱 Первый пост');if(likes>=10)add('👍 10 лайков');if(followers>=50)add('🎉 50 подписчиков');if(threads>=3)add('🧶 3 нити');if(comments>=10)add('💬 10 комментариев');if(clubs>=5)add('🧑‍🤝‍🧑 5 клубков');CU.achievements=a;save();}
function applyTheme(){document.body.className=D.theme||'dark';}
function toggleTheme(){D.theme=D.theme==='light'?'dark':'light';save();applyTheme();}

function showProfileModal(){const list=$('profileList');const users=Object.values(U);list.innerHTML=users.length?users.map(u=>`<div class="profile-list-item" onclick="selectProfile('${u.id}')" style="display:flex;align-items:center;gap:10px;padding:10px;background:#0f3460;border-radius:10px;margin:5px 0;cursor:pointer;">${av(u)} <span>${u.name}</span></div>`).join(''):'<p>Нет профилей</p>';$('newName').value='';$('avatarInput').value='';$('profileModal').style.display='flex';}
function closeProfileModal(){$('profileModal').style.display='none';if(!CU)showProfileModal();}
function selectProfile(uid){D.currentUserId=uid;save();CUID=uid;CU=U[uid];closeProfileModal();updateHeader();switchTab('feed');}
function createProfile(){const name=$('newName').value.trim();if(!name)return alert('Введите имя');const file=$('avatarInput').files[0];const uid='u_'+Date.now();const isFirst=Object.keys(U).length===0;const user={id:uid,name,avatar:null,isCreator:isFirst,premium:false,subscribedAuthors:[],subscribedThreads:[],achievements:[],pinnedPostId:null,pinnedThreadId:null};U[uid]=user;if(file){const fr=new FileReader();fr.onload=e=>{user.avatar=e.target.result;D.currentUserId=uid;save();CUID=uid;CU=user;closeProfileModal();updateHeader();switchTab('feed');achievements();};fr.readAsDataURL(file);}else{D.currentUserId=uid;save();CUID=uid;CU=user;closeProfileModal();updateHeader();switchTab('feed');achievements();}}
function switchProfile(){showProfileModal();}
function updateHeader(){if(CU){const a=av(CU);authArea.innerHTML=`${a} ${CU.name} ${role(CU)} <button onclick="switchProfile()" class="primary" style="padding:4px 10px;">🔄</button>`;}else{authArea.innerHTML=`<button onclick="showProfileModal()" class="primary" style="padding:4px 10px;">Войти</button>`;}updateBell();}

document.querySelectorAll('.nav-btn').forEach(b=>b.addEventListener('click',()=>{const t=b.dataset.tab;if(!CU&&t!=='feed')return showProfileModal();switchTab(t);}));
function switchTab(t){document.querySelectorAll('.nav-btn').forEach(b=>b.classList.remove('active'));document.querySelector(`.nav-btn[data-tab="${t}"]`)?.classList.add('active');if(t==='feed')renderFeed();else if(t==='explore')renderExplore();else if(t==='create')renderCreatePost();else if(t==='messages')renderMessages();else if(t==='clubs')renderClubs();}

let feedMode='all';
function renderFeed(){let posts=[];if(CU){const subs=CU.subscribedThreads||[];posts=subs.length?Object.values(P).filter(p=>subs.includes(p.threadId)):[];}else{posts=Object.values(P);}const q=document.getElementById('searchInput')?.value.trim().toLowerCase()||'';if(q)posts=posts.filter(p=>p.content.toLowerCase().includes(q)||p.authorName.toLowerCase().includes(q));if(feedMode==='popular'){posts=posts.filter(p=>(Date.now()-p.createdAt)<86400000);posts.sort((a,b)=>(b.likes?.length||0)-(a.likes?.length||0));posts=posts.slice(0,10);}else if(feedMode==='unread'&&CU){const read=D.readPosts[CUID]||[];posts=posts.filter(p=>!read.includes(p.id));}else{posts.sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));}let html=`<div class="search-bar"><input id="searchInput" placeholder="Поиск... 🔍" oninput="renderFeed()"></div><div style="display:flex;gap:10px;margin-bottom:15px;"><button onclick="feedMode='all';renderFeed();" class="primary" style="${feedMode==='all'?'box-shadow:0 0 10px #00ffff;':''}">Все</button><button onclick="feedMode='popular';renderFeed();" class="primary">Популярное</button><button onclick="feedMode='unread';renderFeed();" class="primary">Непрочитанное</button></div>`;posts.forEach(p=>html+=renderPostCard(p));content.innerHTML=html||'<p>Пока нет постов.</p>';}
function renderPostCard(p){const author=U[p.authorId]||{name:'Аноним'};let media='';if(p.mediaUrls?.length){if(p.type==='video')media=`<video src="${p.mediaUrls[0]}" controls></video>`;else media=renderCarousel(p);}return `<div class="card post-card" id="post-${p.id}"><div style="display:flex;align-items:center;gap:10px;">${av(author)}<div><strong>${p.authorName}</strong> ${role(author)} <span style="color:#00ffff;">в «${p.threadName||''}»</span></div></div><p>${p.content}</p>${media}<div style="display:flex;gap:10px;align-items:center;margin-top:10px;">${CU?`<button class="likes-btn" onclick="toggleLike('${p.id}')">${p.likes?.includes(CUID)?'❤️':'🤍'} ${p.likes?.length||0}</button><button onclick="toggleComments('${p.id}')">💬 ${p.comments?.length||0}</button><button onclick="sharePost('${p.id}')">🔗</button>`:`<button class="login-prompt" onclick="showProfileModal()">❤️ ${p.likes?.length||0}</button>`}<span style="cursor:pointer;color:#ff00ff;" onclick="switchTab('profile');renderProfile('${p.authorId}')">👤 Профиль</span></div><div id="comments-${p.id}" style="display:none;margin-top:10px;"></div></div>`;}
function renderCarousel(p){if(!p.mediaUrls||p.mediaUrls.length===1)return `<img src="${p.mediaUrls[0]}" style="max-width:100%;border-radius:12px;">`;let imgs=p.mediaUrls.map((url,i)=>`<img src="${url}" class="carousel-img ${i===0?'active':''}" data-post="${p.id}" data-index="${i}">`).join('');return `<div class="carousel" id="carousel-${p.id}">${imgs}<button class="prev" onclick="changeSlide('${p.id}',-1)">‹</button><button class="next" onclick="changeSlide('${p.id}',1)">›</button></div>`;}
function changeSlide(pid,dir){const car=document.getElementById(`carousel-${pid}`);if(!car)return;const imgs=car.querySelectorAll('.carousel-img');const active=car.querySelector('.active');let idx=parseInt(active.dataset.index);idx=(idx+dir+imgs.length)%imgs.length;imgs.forEach(i=>i.classList.remove('active'));imgs[idx].classList.add('active');}

function toggleComments(pid){if(!CU)return showProfileModal();const div=document.getElementById(`comments-${pid}`);if(div.style.display==='block'){div.style.display='none';return;}const post=P[pid];const coms=post.comments||[];div.innerHTML=coms.map(c=>{const u=U[c.userId]||{};return`<div><strong>${c.userName}</strong> ${role(u)}: ${c.text}</div>`;}).join('')+`<input id="commInput-${pid}" placeholder="Комментарий..."><button onclick="submitComment('${pid}')">Отправить</button>`;div.style.display='block';if(!D.readPosts[CUID])D.readPosts[CUID]=[];if(!D.readPosts[CUID].includes(pid)){D.readPosts[CUID].push(pid);save();}}
function submitComment(pid){const inp=document.getElementById(`commInput-${pid}`);const text=inp.value.trim();if(!text)return;const post=P[pid];if(!post.comments)post.comments=[];post.comments.push({userId:CUID,userName:CU.name,text,time:Date.now()});notif(post.authorId,'comment',CUID,{postId:pid});save();toggleComments(pid);}
function toggleLike(pid){if(!CU)return showProfileModal();const post=P[pid];const idx=post.likes.indexOf(CUID);if(idx===-1){post.likes.push(CUID);notif(post.authorId,'like',CUID,{postId:pid});}else{post.likes.splice(idx,1);}save();renderFeed();}
function sharePost(pid){const link=`${location.origin}${location.pathname}#post-${pid}`;navigator.clipboard.writeText(link).then(()=>alert('Ссылка скопирована!'));}

function renderCreatePost(){if(!CU)return showProfileModal();content.innerHTML=`<h2 style="color:#00ffff;">Новый пост</h2><input id="threadName" placeholder="Название нити (по умолчанию «Основная»)"><textarea id="postText" placeholder="Что нового?"></textarea><div><label class="primary" style="cursor:pointer;">📷 Фото (до 4) <input type="file" id="imageInput" accept="image/*" multiple style="display:none;" onchange="previewImages()"></label><label class="primary" style="cursor:pointer;">🎬 Видео <input type="file" id="videoInput" accept="video/*" style="display:none;" onchange="previewVideo()"></label></div><div id="mediaPreview" style="margin-top:10px;"></div><button onclick="publishPost()" class="primary" style="width:100%;">Опубликовать</button>`;window.tmp={type:null,urls:[]};}
function previewImages(){const files=document.getElementById('imageInput').files;if(!files.length)return;const prev=document.getElementById('mediaPreview');prev.innerHTML='';window.tmp={type:'image',urls:[]};Array.from(files).slice(0,4).forEach(file=>{const r=new FileReader();r.onload=e=>{window.tmp.urls.push(e.target.result);prev.innerHTML+=`<img src="${e.target.result}" style="max-width:100px;margin:5px;">`;};r.readAsDataURL(file);});}
function previewVideo(){const file=document.getElementById('videoInput').files[0];if(!file)return;const url=URL.createObjectURL(file);window.tmp={type:'video',urls:[url]};document.getElementById('mediaPreview').innerHTML=`<video src="${url}" controls style="max-width:200px;"></video>`;}
function publishPost(){const text=document.getElementById('postText').value.trim();const threadName=document.getElementById('threadName').value.trim()||'Основная';let tid=Object.values(T).find(t=>t.ownerId===CUID&&t.name===threadName&&t.type==='user')?.id;if(!tid){tid='t_'+Date.now();T[tid]={id:tid,name:threadName,ownerId:CUID,type:'user',createdAt:Date.now()};for(let uid in U)if(U[uid].subscribedAuthors.includes(CUID))U[uid].subscribedThreads.push(tid);}if(!CU.subscribedThreads.includes(tid))CU.subscribedThreads.push(tid);const post={id:'p_'+Date.now(),content:text,type:window.tmp.type||'text',mediaUrls:window.tmp.urls||[],threadId:tid,threadName,authorId:CUID,authorName:CU.name,createdAt:Date.now(),likes:[],comments:[]};P[post.id]=post;save();achievements();window.tmp={type:null,urls:[]};switchTab('feed');}

function renderProfile(uid){if(!CU)return showProfileModal();const p=U[uid];if(!p)return alert('Пользователь не найден');const isMe=uid===CUID;const sub=!!CU.subscribedAuthors?.includes(uid);const threads=Object.values(T).filter(t=>t.ownerId===uid&&t.type==='user');const posts=Object.values(P).filter(p=>p.authorId===uid).sort((a,b)=>b.createdAt-a.createdAt);const followers=Object.values(U).filter(u=>u.subscribedAuthors?.includes(uid)).length;const following=p.subscribedAuthors?.length||0;const totalLikes=posts.reduce((s,p)=>s+(p.likes?.length||0),0);let html=`<div class="card profile-card" style="animation:none;"><div style="display:flex;align-items:center;gap:15px;">${p.avatar?`<img src="${p.avatar}" class="avatar" style="width:70px;height:70px;">`:`<div class="avatar donut" style="width:70px;height:70px;font-size:36px;">🍩</div>`}<div><h2>${p.name}</h2>${role(p)}</div></div><div class="stats"><div><span>${followers}</span> подписчиков</div><div><span>${following}</span> подписок</div><div><span>${totalLikes}</span> лайков</div></div>${p.achievements?.length?`<div>${p.achievements.map(a=>`<span class="achievement">${a}</span>`).join('')}</div>`:''}${!isMe?`<div style="margin:10px 0;"><button onclick="toggleAuthorSubscribe('${uid}')" class="primary">${sub?'Отписаться':'Подписаться'}</button><button onclick="startDialog('${uid}')" class="primary">💬 Написать</button>${CU.isCreator&&!p.isCreator?`<button onclick="togglePremium('${uid}')" class="primary" style="background:gold;">${p.premium?'Убрать премиум':'Дать премиум'}</button>`:''}</div>`:''}<h3>Нити ${p.pinnedThreadId?'<span class="pin-badge">📌 закреп</span>':''}</h3><div style="display:flex;flex-wrap:wrap;gap:10px;">${threads.map(t=>`<div class="card" style="flex:1;min-width:130px;">🧵 ${t.name}${isMe?`<button onclick="togglePinThread('${t.id}')" class="primary" style="font-size:0.7rem;">${p.pinnedThreadId===t.id?'Открепить':'Закрепить'}</button>`:''}${!isMe?`<button onclick="toggleThreadSubscribe('${t.id}')" class="primary" style="font-size:0.7rem;">${CU.subscribedThreads?.includes(t.id)?'Отписаться':'Подписаться'}</button>`:''}</div>`).join('')||'<p>Нет нитей</p>'}</div><h3>Посты ${p.pinnedPostId?'<span class="pin-badge">📌 закреп</span>':''}</h3></div>`;if(p.pinnedPostId&&P[p.pinnedPostId])html+=renderPostCard(P[p.pinnedPostId]);posts.filter(po=>po.id!==p.pinnedPostId).forEach(po=>html+=renderPostCard(po));content.innerHTML=html;}
function toggleAuthorSubscribe(aid){const idx=CU.subscribedAuthors.indexOf(aid);if(idx===-1){CU.subscribedAuthors.push(aid);Object.values(T).forEach(t=>{if(t.ownerId===aid&&t.type==='user'&&!CU.subscribedThreads.includes(t.id))CU.subscribedThreads.push(t.id);});notif(aid,'subscribe',CUID);}else{CU.subscribedAuthors.splice(idx,1);const tids=Object.values(T).filter(t=>t.ownerId===aid).map(t=>t.id);CU.subscribedThreads=CU.subscribedThreads.filter(id=>!tids.includes(id));}save();switchTab('profile');}
function toggleThreadSubscribe(tid){const idx=CU.subscribedThreads.indexOf(tid);if(idx===-1)CU.subscribedThreads.push(tid);else CU.subscribedThreads.splice(idx,1);save();switchTab('profile');}
function togglePremium(uid){if(!CU.isCreator)return;U[uid].premium=!U[uid].premium;save();switchTab('profile');}
function togglePinPost(pid){CU.pinnedPostId=CU.pinnedPostId===pid?null:pid;save();renderProfile(CUID);}
function togglePinThread(tid){CU.pinnedThreadId=CU.pinnedThreadId===tid?null:tid;save();renderProfile(CUID);}

function renderMessages(){if(!CU)return showProfileModal();const d=Object.entries(M).filter(([_,v])=>v.participants.includes(CUID));let html='<h2>💬 Чаты</h2>';if(!d.length)html+='<p>Нет диалогов.</p>';else d.forEach(([id,v])=>{const oid=v.participants.find(p=>p!==CUID);const other=U[oid];html+=`<div class="card" onclick="openDialog('${id}')"><strong>${other?.name||'Неизвестный'}</strong><p>${v.lastMessage||''}</p></div>`;});content.innerHTML=html;}
function startDialog(oid){const exist=Object.entries(M).find(([_,v])=>v.participants.includes(CUID)&&v.participants.includes(oid));if(exist)openDialog(exist[0]);else{const id='m_'+Date.now();M[id]={participants:[CUID,oid],msgs:[],lastMessage:''};save();openDialog(id);}}
function openDialog(did){const d=M[did];const oid=d.participants.find(p=>p!==CUID);const other=U[oid];let html=`<h2>Диалог с ${other?.name||'?'}</h2><div id="mc-${did}" style="max-height:400px;overflow-y:auto;margin-bottom:10px;">`;d.msgs.forEach(m=>html+=`<p><strong>${m.from===CUID?'Вы':other?.name}:</strong> ${m.text}</p>`);html+=`</div><input id="mi-${did}" placeholder="Сообщение..."><button onclick="sendMsg('${did}')" class="primary">Отправить</button>`;content.innerHTML=html;const mc=document.getElementById(`mc-${did}`);if(mc)mc.scrollTop=mc.scrollHeight;}
function sendMsg(did){const inp=document.getElementById(`mi-${did}`);const text=inp.value.trim();if(!text)return;const d=M[did];d.msgs.push({from:CUID,text,time:Date.now()});d.lastMessage=text;save();openDialog(did);}

function renderClubs(){if(!CU)return showProfileModal();const clubs=Object.values(T).filter(t=>t.type==='club');let html='<h2>🧶 Клубки</h2><button onclick="renderCreateClub()" class="primary">+ Создать</button>';clubs.forEach(c=>{const m=c.members.includes(CUID);html+=`<div class="card"><h3>${c.name}</h3><p>Участников: ${c.members.length}</p><button onclick="${m?'leaveClub':'joinClub'}('${c.id}')" class="primary">${m?'Выйти':'Вступить'}</button>${m?`<button onclick="switchTab('create')" class="primary">Пост</button>`:''}${CU.isCreator||c.ownerId===CUID?`<button onclick="promoteAdmin('${c.id}')" class="primary">👑 Админ</button>`:''}</div>`;});content.innerHTML=html;}
function renderCreateClub(){content.innerHTML=`<h2>Создать клубок</h2><input id="clubName" placeholder="Название"><textarea id="clubDesc" placeholder="Описание"></textarea><button onclick="createClub()" class="primary">Создать</button>`;}
function createClub(){const name=$('clubName').value.trim();if(!name)return;const desc=$('clubDesc').value.trim();const id='c_'+Date.now();T[id]={id,name,description:desc,type:'club',ownerId:CUID,members:[CUID],admins:[CUID],createdAt:Date.now()};CU.subscribedThreads.push(id);if(!CU.adminClubs)CU.adminClubs=[];CU.adminClubs.push(id);save();switchTab('clubs');}
function joinClub(cid){T[cid].members.push(CUID);CU.subscribedThreads.push(cid);save();switchTab('clubs');}
function leaveClub(cid){T[cid].members=T[cid].members.filter(id=>id!==CUID);CU.subscribedThreads=CU.subscribedThreads.filter(id=>id!==cid);save();switchTab('clubs');}
function promoteAdmin(cid){const uid=prompt('ID пользователя:');if(!uid)return;if(!T[cid].admins)T[cid].admins=[];T[cid].admins.push(uid);if(U[uid]){if(!U[uid].adminClubs)U[uid].adminClubs=[];U[uid].adminClubs.push(cid);notif(uid,'admin',CUID,{clubId:cid});}save();renderClubs();}

function renderExplore(){const q=document.getElementById('exploreSearch')?.value.trim().toLowerCase()||'';const ft=Object.values(T).filter(t=>t.type==='user'&&t.name.toLowerCase().includes(q));let html=`<h2>🌍 Обзор</h2><input id="exploreSearch" placeholder="Поиск нитей..." oninput="renderExplore()"><h3>Нити</h3>`;ft.forEach(t=>{html+=`<div class="card" style="padding:10px;">🧵 ${t.name} (автор: ${U[t.ownerId]?.name||'?'})${CU&&!CU.subscribedThreads.includes(t.id)?`<button onclick="toggleThreadSubscribe('${t.id}')" class="primary" style="font-size:0.7rem;">Подписаться</button>`:''}</div>`;});html+='<h3>Пользователи</h3>';Object.values(U).forEach(u=>{html+=`<div class="card" style="padding:10px;display:flex;align-items:center;gap:10px;">${av(u)} ${u.name}${CU&&u.id!==CUID?`<button onclick="toggleAuthorSubscribe('${u.id}')" class="primary" style="font-size:0.7rem;">${CU.subscribedAuthors?.includes(u.id)?'Отписаться':'Подписаться'}</button>`:''}</div>`;});content.innerHTML=html;}

applyTheme();
updateHeader();
